{% set name = "sagemaker-studio-image-build" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_studio_image_build-{{ version }}.tar.gz
  sha256: b7586597ca2395a63e463f8e3ab981ae987d5ea500bf86096af9a79dc41ec9b5

build:
  number: 1
  noarch: python
  entry_points:
    - sm-docker=sagemaker_studio_image_build.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - boto3 >=1.10.44,<2.0
    - python >={{ python_min }}
    - sagemaker <3.0

test:
  imports:
    - sagemaker_studio_image_build
  commands:
    - pip check
    - sm-docker --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws-samples/sagemaker-studio-image-build-cli
  summary: Build Docker Images in Amazon SageMaker Studio using AWS CodeBuild
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
